[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    cache-control = '''
    no-cache,
    no-store,
    must-revalidate
    private'''

[[redirects]]
  from = "/._darcs"
  to = "/404"
  status = 404


[[redirects]]
  from = "/.bzr"
  to = "/404"
  status = 404
  

[[redirects]]
  from = "/.hg"
  to = "/404"
  status = 404


[[redirects]]
  from = "/.git"
  to = "/404"
  status = 404
  

[[redirects]]
  from = "/.BitKeeper"
  to = "/404"
  status = 404


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  